### ISSUE TITLE
Compilation with latest downloaded repose not working, producing compilation issues...

### ISSUE THREAD

**Issue by rolfeisenhut** [softwarecrash/EPEver2MQTT#14]
Following issue is occuring while compilation... 

just started with; >>> 
` pio run 
`
  command. Running under OS windows 11. Any Idea what wrong.

Compiling .pio\build\esp01_1m\libb53\ESP8266mDNS\LEAmDNS_Helpers.cpp.o
Compiling .pio\build\esp01_1m\libb53\ESP8266mDNS\LEAmDNS_Structs.cpp.o
In file included from .pio\libdeps\esp01_1m\EspSoftwareSerial\src\SoftwareSerial.cpp:23:0:
.pio\libdeps\esp01_1m\EspSoftwareSerial\src\SoftwareSerial.h: In static member function 'static constexpr bool EspSoftwareSerial::GpioCapabilities::hasPullUp(int8_t)':
.pio\libdeps\esp01_1m\EspSoftwareSerial\src\SoftwareSerial.h:102:5: error: body of constexpr function 'static constexpr bool EspSoftwareSerial::GpioCapabilities::hasPullUp(int8_t)' not a return-statement
     }
     ^
.pio\libdeps\esp01_1m\EspSoftwareSerial\src\SoftwareSerial.h: At global scope:
.pio\libdeps\esp01_1m\EspSoftwareSerial\src\SoftwareSerial.h:285:23: warning: 'deprecated' attribute directive ignored [-Wattributes]
     void perform_work();
                       ^
.pio\libdeps\esp01_1m\EspSoftwareSerial\src\SoftwareSerial.h:199:9: error: 'int EspSoftwareSerial::UARTBase::availableForWrite()' marked override, but does not override
     int availableForWrite() override {
         ^
.pio\libdeps\esp01_1m\EspSoftwareSerial\src\SoftwareSerial.h:226:9: error: 'int EspSoftwareSerial::UARTBase::read(uint8_t*, size_t)' marked override, but does not override

**Comment by softwarecrash** [comment]
try it with ```pio run --environment esp01_1m```

**Comment by softwarecrash** [comment]
problem found, the actual espresserif 8266 package is incompatible with the softwareserial (that not used here but in the library list)
on VSC go to platformio->platforms and unintsall all espresserif 8266 platforms, keep only 4.2.0/4.1.0
