### ISSUE TITLE
[Bug]: BATT_AMPS & BATT_WATTS wrong readings

### ISSUE THREAD

**Issue by MatchoLM** [softwarecrash/EPEver2MQTT#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Used Hardware?

Wemos D1 Mini

### What happened?

BATT_AMPS & BATT_WATTS in MQTT and also in web ui did not fit to real battery values, actual values are about total current & power production of Epever regulator. Without used LOAD the values are okay because current or power going only to battery, but in case LOAD is used like in my case the total current or power is devided to load and battery, so correct calculation for battery values should be total amps - load or total watts - load. In case solar panells are not producing enought power, current going from battery to load and on battery should be negative reading of current or power.  

### Screenshots / Fotos

![2](https://github.com/softwarecrash/EPEver2MQTT/assets/105044460/18b943bb-4477-49b5-a9d3-5bd8bba4d2b0)

### Version

1.x.x and above

### Relevant livejson output

```json
{"LiveData":{"SOLAR_VOLTS":95.22,"SOLAR_AMPS":0.95,"SOLAR_WATTS":90.95,"BATT_VOLTS":25.84,"BATT_AMPS":3.52,"BATT_WATTS":90.95,"LOAD_VOLTS":25.84,"LOAD_AMPS":3.47,"LOAD_WATTS":89.66,"BATTERY_SOC":55},"StatsData":{"SOLAR_MAX":109.85,"SOLAR_MIN":4.96,"BATT_MAX":26.2,"BATT_MIN":25.12,"CONS_ENERGY_DAY":0.83,"CONS_ENGERY_MON":7.46,"CONS_ENGERY_YEAR":7.46,"CONS_ENGERY_TOT":7.76,"GEN_ENERGY_DAY":0.26,"GEN_ENERGY_MON":7.1,"GEN_ENERGY_YEAR":7.1,"GEN_ENERGY_TOT":7.52,"CO2_REDUCTION":0},"DEVICE_NAME":"EPEver2MQTT","DEVICE_QUANTITY":1,"DEVICE_TIME":1690359108,"DEVICE_TEMPERATURE":32.07,"DEVICE_FREE_HEAP":35528,"DEVICE_JSON_MEMORY":653,"ESP_VCC":2.991,"Wifi_RSSI":-66,"BATTERY_TEMPERATURE":20.55,"LOAD_STATE":true,"BATT_VOLT_STATUS":"Normal","BATT_TEMP":"Normal","CHARGER_INPUT_STATUS":"Normal","CHARGER_MODE":"Boost"}
```

### What browsers are you seeing the problem on?

Chrome

**Comment by softwarecrash** [comment]
we dont do any calculations on the ESP, all you see is what we get from the EPever device
check the coresponding datasheet:
https://github.com/softwarecrash/EPEver2MQTT/blob/main/Protocol/ControllerProtocolV2.3.pdf

**Comment by MatchoLM** [comment]
thx for reply, i checked datasheet and i find there are two adresses for battery current 331B and 331C can we test it ? please see reading from Solar Station MonitorV1.95 got me calculatred value
 ![1](https://github.com/softwarecrash/EPEver2MQTT/assets/105044460/60dd947f-3c54-4e0f-ae03-02e6ef227c1e)

**Comment by softwarecrash** [comment]
I dont know solar Station Monitor, ITS possibile that this Males calculations based in the Data
These two Data field dont need Testing, its marked with H and L that mean that this is a high and Low Byte and need shiftet to one dataset.
But I have seen some curios Data structure ordering, il Check it Later.

Unfourtanley i dont have a epever device Here, @all-solutions have one and can Check it.
We must wait for him

**Comment by MatchoLM** [comment]
-1,12A that was situation when i did not get enought power from solar and current go from battery to load. now should be on battery -3.6A but shows 0A -battery shows now value of total amps generated by charger/regulator
![image](https://github.com/softwarecrash/EPEver2MQTT/assets/105044460/64967855-265a-4d8b-b1c5-0470be4b3d9a)

**Comment by softwarecrash** [comment]
now its clearer, let me check that the next days

**Comment by MatchoLM** [comment]
yeah sure thx so much :) i found picture from regulator, just to be 100% clear , solar panel got just few watts or amps so load was 2,8A , from battery was taken -2,4A 
![image](https://github.com/softwarecrash/EPEver2MQTT/assets/105044460/a790dc45-0491-438f-9699-b39e5dac3fe1)

**Comment by softwarecrash** [comment]
so understand right,
the batter A must shift to load
and battery A need a new value from 311B/C
right?

**Comment by MatchoLM** [comment]
produced Amps are divided to battery and loads like example production is 20A loads is 5A then battery get 15A. if is production Amps lower than loads Amps like example 2A producced, loads 5A  then battery should show negative readings -3A because current from production is not enought and must be taken from battery

**Comment by softwarecrash** [comment]
[EPEver2MQTT_d1_mini_1.1.1-1.zip](https://github.com/softwarecrash/EPEver2MQTT/files/12176985/EPEver2MQTT_d1_mini_1.1.1-1.zip)
check this please, batt amp have now the value from 311B/C

**Comment by MatchoLM** [comment]
for now it looks better, i will see tomorrow when sun came out and start some production :) 
![image](https://github.com/softwarecrash/EPEver2MQTT/assets/105044460/1aacfd8b-8749-493e-b86a-d20233461585)

**Comment by softwarecrash** [comment]
ok, watt cannot correct, that must be a calculated value or removed, i never seen this as negative

**Comment by MatchoLM** [comment]
could be if you dont use load terminals on charger. benefit of using load terminals is you can monitor your real load what is not possible if you connect load directly to battery, and also when is load connected directly to battery you can not switch off load via regulator and on battery stats you will get Amps and Watts from battery + loads together. on my epever xtra4415n there are loads terminals up to 40A so no problem to use them for 500/1000w inverter :) 
![image](https://github.com/softwarecrash/EPEver2MQTT/assets/105044460/639cd91f-65d5-4c2e-b5bf-2333ca034bd4)

**Comment by softwarecrash** [comment]
[EPEver2MQTT_d1_mini_1.1.1-2.zip](https://github.com/softwarecrash/EPEver2MQTT/files/12177127/EPEver2MQTT_d1_mini_1.1.1-2.zip)
for the case the values are right, here the .1-2 with corrected amp and watt values for the battery
please report

**Comment by MatchoLM** [comment]
in this case watts are calculated with wrong decimal point -95.49W should be ok. 
![image](https://github.com/softwarecrash/EPEver2MQTT/assets/105044460/d617330d-37ac-4bb5-92d7-ef6d85a620b2)

**Comment by softwarecrash** [comment]
what the heck? too late for calculations, i hope this will fit
[EPEver2MQTT_d1_mini_1.1.1-3.zip](https://github.com/softwarecrash/EPEver2MQTT/files/12177196/EPEver2MQTT_d1_mini_1.1.1-3.zip)

**Comment by MatchoLM** [comment]
yeah now is okay :) i let you know tomorrow how it works with produced power from solar panel, anyhow now is too late and both of us need some beer haha. Thank you for quick responses and findings.
![image](https://github.com/softwarecrash/EPEver2MQTT/assets/105044460/1c843c3e-8c5e-4836-90dd-e87b47b0c115)

**Comment by softwarecrash** [comment]
jep,
just for test, will the watt with this correct and with 2 decimal places
[EPEver2MQTT_d1_mini_1.1.1-4.zip](https://github.com/softwarecrash/EPEver2MQTT/files/12177289/EPEver2MQTT_d1_mini_1.1.1-4.zip)

**Comment by MatchoLM** [comment]
this version does wrong decimals
![image](https://github.com/softwarecrash/EPEver2MQTT/assets/105044460/45352e2d-cc12-4605-be16-bec96f1c8820)

**Comment by softwarecrash** [comment]
lol what a mess... my calculator does it right
last try for now
[EPEver2MQTT_d1_mini_1.1.1-5.zip](https://github.com/softwarecrash/EPEver2MQTT/files/12177380/EPEver2MQTT_d1_mini_1.1.1-5.zip)

**Comment by MatchoLM** [comment]
it is too late also for calculator haha 
![image](https://github.com/softwarecrash/EPEver2MQTT/assets/105044460/205e18e2-34dc-4513-b9a3-d9035a904ed7)

**Comment by softwarecrash** [comment]
the decimal thing i will fix later....
so what is production for data? can you pull out the data points from the pdf and sort it to the places?

**Comment by MatchoLM** [comment]
"production" data will show total Amps produced by regulator and i like to have it to see also total produced Apms, that would be same value like was before on battery position in version 1.1.0 like i call it "total" on first post picture

**Comment by softwarecrash** [comment]
theoretical possibile, but its like the watt on battery, its not the best way to calculate some data.
so we need a new layout ore ordering / sorting of the avaible data. 
so when you have a idea, make a picture with a sorting / layout with places marked witht the hex data field and value like (311C)W

**Comment by MatchoLM** [comment]
i checked with Controller Protocol V2.v3.pdf and also with Epever Solar Station Monitor 1.95 but i did not find corresponding value for it. so i see only possibility to use previous code of battery colum for new one "production" which should be easiest way or then is second option which is from my point of you more precise, from v1.1.1-5 take values of battery and load and calculate them together batt+load and that is equal to total production of regulator. I expect calculated value (W) should be different then readings W from solar because conversion efeciency of regulator is flexible.
![image](https://github.com/softwarecrash/EPEver2MQTT/assets/105044460/64bfc9d4-0fc9-4c99-8a14-51a6ecbbb2f9)

**Comment by softwarecrash** [comment]
thanks.
i must fix another thing, then i will look that i make the data right

**Comment by MatchoLM** [comment]
yeah sure , thank you ! :)

**Comment by softwarecrash** [comment]
i have revertet something, and corrected the battery Ampere value.
can you check the battery Watt value when the batery ampere goes negativ?

in wrong case i think to remove the battery watt data, these are similar to the solar watt data and the epever doesnt provide the battery watt value
[EPEver2MQTT_esp01_1m_1.1.1-6.zip](https://github.com/softwarecrash/EPEver2MQTT/files/12213625/EPEver2MQTT_esp01_1m_1.1.1-6.zip)

**Comment by MatchoLM** [comment]
can you please upload d1_mini version ?

**Comment by softwarecrash** [comment]
ops, my fault. here with mini
[EPEver2MQTT_d1_mini_1.1.1-7.zip](https://github.com/softwarecrash/EPEver2MQTT/files/12214078/EPEver2MQTT_d1_mini_1.1.1-7.zip)

**Comment by MatchoLM** [comment]
i checked it and watts are not correct on both scenarios in positive readings there value from solar and in negative scenario is issue same, value from solar. Correct watts was in version 1.1.1-3 there was just small thing about to many numbers after dot what is from my point of you no any mistake. btw why do you like to avoid some calculations in your code?
![image](https://github.com/softwarecrash/EPEver2MQTT/assets/105044460/ebbdbde3-e1b9-424c-9090-a7dcb1e5d732)
![image](https://github.com/softwarecrash/EPEver2MQTT/assets/105044460/63c3cea7-6d3e-4711-b622-4afcb92a67c3)

**Comment by softwarecrash** [comment]
im on it.
why avoid calculations? its a relativ big code impact, or other the cpu need a lot of cycles to calculate two float values into one and correct the decimal places, but i look that i can make it.
on the other side, i get now a epever and rewrite some things

**Comment by MatchoLM** [comment]
that sounds great :) if you will need any help with testing or something just let me know.

**Comment by softwarecrash** [comment]
i think i have managed the watt value and the negative battery.
please check
[EPEver2MQTT_d1_mini_1.1.1-8.zip](https://github.com/softwarecrash/EPEver2MQTT/files/12262226/EPEver2MQTT_d1_mini_1.1.1-8.zip)

**Comment by MatchoLM** [comment]
it looks okey :) good job :) 

![image](https://github.com/softwarecrash/EPEver2MQTT/assets/105044460/8cade1dc-ca77-4be4-a0bb-81b6d73f4f19)

**Comment by softwarecrash** [comment]
great, it will comes offizial with the next release

**Comment by MatchoLM** [comment]
thx so much :)
