### ISSUE TITLE
Static IP settings

### ISSUE THREAD

**Issue by cweigl** [softwarecrash/EPEver2MQTT#20]
### Is your feature request related to a problem? Please describe

Static IP settings are not possible now. To choose between automatic and static IP settings would be a great feature.
Thank you

### Describe the solution you'd like

Add possibility for static ip settings in Wifi configuration.
Thank you

### Describe alternatives you've considered

For example: checkbox  "DHCP",..
DHCP activated, static IP address configuration is unactiveted,
if active, IP Address, subnet, gateway, dns,.. can be set up.

**Comment by softwarecrash** [comment]
I have checked it, with the actual wifi manager this is not possible. sorry
