### ISSUE TITLE
[Bug]: Typo: Temperature shown a Gemperature Vers. 2.0.0

### ISSUE THREAD

**Issue by Emmpunkt** [softwarecrash/EPEver2MQTT#21]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Used Hardware?

Wemos D1 Mini

### What happened?

Title says all, nothing more to tell...

### Screenshots / Fotos

![Screenshot 2023-08-21 144137](https://github.com/softwarecrash/EPEver2MQTT/assets/19502874/b5fa9104-7c85-44fd-8d18-c0398944b245)

### Version

1.x.x and above

### Relevant livejson output

```json
Don.t know what i should paste here
```

### What browsers are you seeing the problem on?

Chrome

**Comment by softwarecrash** [comment]
thank you for the hint.
it will be fixed with the next release

**Comment by softwarecrash** [comment]
Fixed with V2.0.1
