### ISSUE TITLE
Battery and device temperature desired

### ISSUE THREAD

**Issue by Renz40** [softwarecrash/EPEver2MQTT#3]
Thank you so much for the software!
I run it on a 8266 to read my EPEVER XTRA3415N devices and publish MQTT.

It would be very nice to have the temperatures as well.
My XTRA3415N has the battery temperature at offset 12560 and the device temperature at offset 12561.
Each temperature comes in a single (16 bit) register and is scaled as °C times 100.
For example 18.9 °C is shown as 1890 decimal.
Temperatures below 0 °C are reported as negative values.
Thanks again!

**Comment by softwarecrash** [comment]
added with V0.2.3
