### ISSUE TITLE
Effekta AX M1 3000W 48V

### ISSUE THREAD

**Issue by Lutz512** [softwarecrash/EPEver2MQTT#35]
### What device are you using?

At least for the Effekta AX M1 3000VA 48V you surely need to replace the builtin USB interface card with the interface card that is shipped with the in Gemany so called "EFFEKTA AX-SERIE EXTERNES WIFI MODUL MONITORING BOX", GTIN: 7426754264520.  

The device occours asmodel VM-5000 and uses the procotol PI30. It is stable working.

Effekta inverters with 5000VA an above seem to have this card already inside. I am not sure.
Also not sure if the newer Serie Effekta AX M2 works

**Comment by softwarecrash** [comment]
thank you
