### ISSUE TITLE
Typo in charger_charging_status

### ISSUE THREAD

**Issue by sdalu** [softwarecrash/EPEver2MQTT#43]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Used Hardware?

Wemos D1 Mini

### What happened?

The letter "a" is missing
https://github.com/softwarecrash/EPEver2MQTT/blob/576ec65649fed65ac5ec8a1a00ffebef432e49a8/src/epregister.h#L262

### Screenshots / Fotos

n/a

### Version

1.x.x and above

### Relevant livejson output

```json
.
```

### What browsers are you seeing the problem on?

no Issue with the Browser or WebUI

**Comment by softwarecrash** [comment]
thank you, is fixed
