### ISSUE TITLE
Reset/Clear Error on Epever

### ISSUE THREAD

**Issue by derFrickler** [softwarecrash/EPEver2MQTT#5]
From time to time my EPEVER Charger refuses to charge - i guess its due to my BMS switching of the battery because of low-temp of low charge). 
Even after the battery is back on again, the EPEVER is refusing to start charging again. Sometimes i need to press Enter on the charger, sometime i need to restart it to make it start charging again. 

It would be nice if this could be triggered from the webinterface. 
I found this post where they say that sending a cmd via modbus should clear the error. 
https://www.photovoltaikforum.com/thread/189334-epever-tracer-laderegler-fehler-reset-via-rs485-modbus/
It would be great if that could be added to the webinterface.

**Comment by softwarecrash** [comment]
Thanks, 
I will Check this later.
When possibil i add an webhook Option for a reset.

**Comment by softwarecrash** [comment]
have you any idea how to generate a error?

**Comment by softwarecrash** [comment]
sorry, but there is no coil that react and clear the error states

**Comment by derFrickler** [comment]
Sorry, i was off the last days. 
Found out that my BMS seems to be the problem. Might have killed the charging FETs due to overcurrent the last cold and sunny days.

**Comment by softwarecrash** [comment]
no problem.
so the reset function is a nice idea, but i cant find any register / coil to do that
