### ISSUE TITLE
[HELP] 226 Read registers for clock failed

### ISSUE THREAD

**Issue by kraftandreas** [softwarecrash/EPEver2MQTT#52]
### A clear and concise description of what the problem is.

I followed the instructions entirely including hardware. I keep getting the error above. 

I have a tracer 4210an and already tried reversing A and B on the modbus side which didn’t change anything. 

Can anyone help?

**Comment by softwarecrash** [comment]
please show your esp wireing and rs module

**Comment by kraftandreas** [comment]
![IMG_2708](https://github.com/user-attachments/assets/3948b958-0dff-4e6b-aa16-5a8b0bb5521f)
![IMG_2709](https://github.com/user-attachments/assets/98e9c3f8-a96b-4354-9c36-5fb055edac3f)

this is reversed polarity A/B. 

From D1 Mini to RS485:
TX -> DI
RX -> RO
D1 -> DE+RE (bridged)

5V -> VCC
GND -> GND

from RS485 to RJ45:

VCC -> ORANGE (Pin 2)
GND -> BROWN (Pin 8)
B -> BLUE (Pin 4)
A -> GREEN (Pin 6)

**Comment by softwarecrash** [comment]
can your verify that U1 is a orginal chip? some china clones doesnt work well

**Comment by kraftandreas** [comment]
![IMG_2710](https://github.com/user-attachments/assets/eac5e0e5-1c6f-4047-8fcb-e163b900e6da)

U1 seems original. I ordered specifically the device that was mentioned. 

I will try powering externally and cut the VCC (and possibly GND) line beforehand. 

Thanks for the quick help!

**Comment by softwarecrash** [comment]
bevor you change anything, try to set the EP device ID to 1, some devices have a changed ID
https://github.com/softwarecrash/EPEver2MQTT/wiki/Multi-Device-Tutorial
use http://<ESP-IP>/set?devid=1
