### ISSUE TITLE
FR: LWT online/offline ESP status

### ISSUE THREAD

**Issue by murfy76** [softwarecrash/EPEver2MQTT#7]
Hi SWcrash,

thank you for your good work on this project. I think it would be nice to have also LWT online/offline status of ESP, thanks.

Peter

**Comment by softwarecrash** [comment]
hi,
thanks, i will add it in next version

**Comment by softwarecrash** [comment]
add int 0.2.4
https://github.com/softwarecrash/EPEver2MQTT/releases/tag/V0.2.4
