### ISSUE TITLE
TLS and dual WiFi

### ISSUE THREAD

**Issue by langsdorff** [softwarecrash/EPEver2MQTT#9]
I use the Software for my rolling Camping Car. IT works great with an 1206AN. I was wondering if adding TLS for MQTT would bei possible? To use it while traveling I start a Hotspot on my phone. When I am static on a campground it would bei great to have a second WiFi setup like tasmota has.
Great work

**Comment by softwarecrash** [comment]
TLS is Not possibil at the Moment, the mqtt library that we Use dont Support that.

For your WiFi Problem a simple fix was to Name your Hotspot on the Phone Dame ad your Home Network with the Same Passwort, the ESP will Connect to both Networks without Change anything.
A Seconds Network is possibil but Not implementet yet
